<?php
// Generated by Zend Framework 2
return array(
    'BricksClassLoaderTest\ClassLoaderTest'     => __DIR__ . '/../../../../H:\Bricks\BricksClassLoader\test\BricksClassLoaderTest/H:/Bricks/BricksClassLoader/test/BricksClassLoaderTest/ClassLoaderTest.php',
    'BricksClassLoaderTest\TestObject'          => __DIR__ . '/../../../../H:\Bricks\BricksClassLoader\test\BricksClassLoaderTest/H:/Bricks/BricksClassLoader/test/BricksClassLoaderTest/TestObject.php',
    'BricksClassLoaderTest\TestObject2'         => __DIR__ . '/../../../../H:\Bricks\BricksClassLoader\test\BricksClassLoaderTest/H:/Bricks/BricksClassLoader/test/BricksClassLoaderTest/TestObject2.php',
    'BricksClassLoaderTest\TestObjectExtended'  => __DIR__ . '/../../../../H:\Bricks\BricksClassLoader\test\BricksClassLoaderTest/H:/Bricks/BricksClassLoader/test/BricksClassLoaderTest/TestObjectExtended.php',
    'BricksClassLoaderTest\TestObjectExtended2' => __DIR__ . '/../../../../H:\Bricks\BricksClassLoader\test\BricksClassLoaderTest/H:/Bricks/BricksClassLoader/test/BricksClassLoaderTest/TestObjectExtended2.php',
);