<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BricksClassLoaderTest\Bootstrap'         => __DIR__ . '/Bootstrap.php',
    'BricksClassLoaderTest\ClassLoaderTest'   => __DIR__ . '/BricksClassLoaderTest/ClassLoaderTest.php',
    'BricksClassLoaderTest\TestObject'        => __DIR__ . '/BricksClassLoaderTest/TestObject.php',
    'BricksClassLoaderTest\TestObjectExtended'=> __DIR__ . '/BricksClassLoaderTest/TestObjectExtended.php',
);
