<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BricksClassLoaderTest\TestObject' => __DIR__ . '/BricksClassLoaderTest/ClassLoaderTest.php',
    'BricksClassLoaderTest\TestObject2'                      => __DIR__ . '/BricksClassLoaderTest/ClassLoaderTest.php',
    'BricksClassLoaderTest\TestObject3'                      => __DIR__ . '/BricksClassLoaderTest/ClassLoaderTest.php',
    'BricksClassLoaderTest\ClassLoaderTest'                  => __DIR__ . '/BricksClassLoaderTest/ClassLoaderTest.php',
);
