<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bricks\ClassLoader\ClassLoader\ClassLoaderAwareInterface'    => __DIR__ . '/src/Bricks/ClassLoader/ClassLoader/ClassLoaderAwareInterface.php',
    'Bricks\ClassLoader\ClassLoader\ClassLoaderInterface'         => __DIR__ . '/src/Bricks/ClassLoader/ClassLoader/ClassLoaderInterface.php',
    'Bricks\ClassLoader\ClassLoader\DefaultClassLoader'           => __DIR__ . '/src/Bricks/ClassLoader/ClassLoader/DefaultClassLoader.php',
    'Bricks\ClassLoader\ClassLoaderService'                       => __DIR__ . '/src/Bricks/ClassLoader/ClassLoaderService.php',
    'Bricks\ClassLoader\ClassLoaderServiceAwareInterface'         => __DIR__ . '/src/Bricks/ClassLoader/ClassLoaderServiceAwareInterface.php',
    'Bricks\ClassLoader\ClassLoaderServiceInterface'              => __DIR__ . '/src/Bricks/ClassLoader/ClassLoaderServiceInterface.php',
    'Bricks\ClassLoader\Factories\ClassLoaderAwareFactory'        => __DIR__ . '/src/Bricks/ClassLoader/Factories/ClassLoaderAwareFactory.php',
    'Bricks\ClassLoader\Factories\ClassLoaderServiceAwareFactory' => __DIR__ . '/src/Bricks/ClassLoader/Factories/ClassLoaderServiceAwareFactory.php',
    'Bricks\ClassLoader\Factories\DefaultFactory'                 => __DIR__ . '/src/Bricks/ClassLoader/Factories/DefaultFactory.php',
    'Bricks\ClassLoader\Factories\FactoryInterface'               => __DIR__ . '/src/Bricks/ClassLoader/Factories/FactoryInterface.php',
    'Bricks\ClassLoader\Factories\InitializerFactory'             => __DIR__ . '/src/Bricks/ClassLoader/Factories/InitializerFactory.php',
    'Bricks\ClassLoader\Instantiators\DefaultInstantiator'        => __DIR__ . '/src/Bricks/ClassLoader/Instantiators/DefaultInstantiator.php',
    'Bricks\ClassLoader\Instantiators\InstantiatorInterface'      => __DIR__ . '/src/Bricks/ClassLoader/Instantiators/InstantiatorInterface.php',
    'Bricks\ClassLoader\ServiceManager\ClassLoaderFactory'        => __DIR__ . '/src/Bricks/ClassLoader/ServiceManager/ClassLoaderFactory.php',
);
