<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bricks\ClassLoader\ClassLoader'                         => __DIR__ . '/src/Bricks/ClassLoader/ClassLoader.php',
    'Bricks\ClassLoader\ClassLoaderAwareInterface'           => __DIR__ . '/src/Bricks/ClassLoader/ClassLoaderAwareInterface.php',
    'Bricks\ClassLoader\Factories\ClassLoaderAwareFactory'   => __DIR__ . '/src/Bricks/ClassLoader/Factories/ClassLoaderAwareFactory.php',
    'Bricks\ClassLoader\Factories\DefaultFactory'            => __DIR__ . '/src/Bricks/ClassLoader/Factories/DefaultFactory.php',
    'Bricks\ClassLoader\Factories\FactoryInterface'          => __DIR__ . '/src/Bricks/ClassLoader/Factories/FactoryInterface.php',
    'Bricks\ClassLoader\Factories\InitializerFactory'        => __DIR__ . '/src/Bricks/ClassLoader/Factories/InitializerFactory.php',
    'Bricks\ClassLoader\Instantiators\DefaultInstantiator'   => __DIR__ . '/src/Bricks/ClassLoader/Instantiators/DefaultInstantiator.php',
    'Bricks\ClassLoader\Instantiators\InstantiatorInterface' => __DIR__ . '/src/Bricks/ClassLoader/Instantiators/InstantiatorInterface.php',
    'Bricks\ClassLoader\ServiceManager\ClassLoaderFactory'   => __DIR__ . '/src/Bricks/ClassLoader/ServiceManager/ClassLoaderFactory.php',
);
