<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BricksClassLoader\Module'                             => __DIR__ . '/Module.php',
    'Bricks\ClassLoader\ClassLoader'                       => __DIR__ . '/src/Bricks/ClassLoader/ClassLoader.php',
    'Bricks\ClassLoader\ClassLoaderAwareInterface'         => __DIR__ . '/src/Bricks/ClassLoader/ClassLoaderAwareInterface.php',
    'Bricks\ClassLoader\ClassLoaderInterface'              => __DIR__ . '/src/Bricks/ClassLoader/ClassLoaderInterface.php',
    'Bricks\ClassLoader\CouldNotInstantiateException'      => __DIR__ . '/src/Bricks/ClassLoader/CouldNotInstantiateException.php',
	'Bricks\ClassLoader\CouldNotLoadException'      	   => __DIR__ . '/src/Bricks/ClassLoader/CouldNotLoadException.php',
    'Bricks\ClassLoader\DefaultClassLoader'                => __DIR__ . '/src/Bricks/ClassLoader/DefaultClassLoader.php',
    'Bricks\ClassLoader\DefaultFactory'                    => __DIR__ . '/src/Bricks/ClassLoader/DefaultFactory.php',
    'Bricks\ClassLoader\DefaultInstantiator'               => __DIR__ . '/src/Bricks/ClassLoader/DefaultInstantiator.php',
    'Bricks\ClassLoader\FactoryInterface'                  => __DIR__ . '/src/Bricks/ClassLoader/FactoryInterface.php',
    'Bricks\ClassLoader\InstantiatorInterface'             => __DIR__ . '/src/Bricks/ClassLoader/InstantiatorInterface.php',
    'Bricks\ClassLoader\ServiceManager\ClassLoaderFactory' => __DIR__ . '/src/Bricks/ClassLoader/ServiceManager/ClassLoaderFactory.php',
    'BricksClassLoaderTest\Bootstrap'                      => __DIR__ . '/test/Bootstrap.php',
    'BricksClassLoaderTest\ClassLoaderTest'                => __DIR__ . '/test/BricksClassLoaderTest/ClassLoaderTest.php',
    'BricksClassLoaderTest\TestObject'                     => __DIR__ . '/test/BricksClassLoaderTest/TestObject.php',
    'BricksClassLoaderTest\TestObjectExtended'             => __DIR__ . '/test/BricksClassLoaderTest/TestObjectExtended.php',
);
